// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
	production: true,
	version: env.npm_package_version,
	serverUrl: 'https://api.newvote.org/api',
	defaultLanguage: 'en-US',
	supportedLanguages: [
		'en-US',
		'fr-FR'
	],
	recaptchaSitekey: '6Lca03AUAAAAALXV7A5FK-noIdCDZ7bpYwWoR2yy'
};
